apiVersion: v1
kind: Service
metadata:
   name: employee-app-service
   namespace: default
spec:
  selector:
    app: employee-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
